name: Build, Test & Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Set up environment variables
        run: |
          echo "DB_NAME=mydatabase" >> $GITHUB_ENV
          echo "DB_USER=myuser" >> $GITHUB_ENV
          echo "DB_PASSWORD=mypassword" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      #- name: Build
       # run: npm run build

      - name: Run tests
        run: npm run test 

      - name: Run linter
        run: npm run lint